[versions]
android-gradle-plugin = "9.3.2"
androidx-activity-compose = "1.13.0"
androidx-compose-bom = "2026.06.01"
androidx-core-ktx = "1.18.0"
desugaring = "2.1.5"
firebase = "34.18.0"
gms = "4.5.0"
gradle-versions-plugin = "0.61.0"
iadvize-sdk = "3.2.0"
kotlin = "2.3.21"
material = "1.14.0"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
desugaring = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugaring" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
iadvize-sdk = { group = "com.iadvize", name = "iadvize-sdk", version.ref = "iadvize-sdk" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
gms = { id = "com.google.gms.google-services", version.ref = "gms" }
gradle-versions-plugin = { id = "io.github.ben-manes.versions", version.ref = "gradle-versions-plugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[bundles]
firebase-tools = ["firebase-analytics", "firebase-messaging"]
