object Versions {
    const val androidxAppCompat = "1.6.1"
    const val androidxCardView = "1.0.0"
    const val androidxConstraintLayout = "2.1.4"
    const val androidxCoreKtx = "1.9.0"
    const val androidxFragment = "1.5.5"
    const val androidxMultiDex = "2.0.1"
    const val androidxNavigation = "2.5.3"
    const val androidxRecyclerView = "1.3.0"
    const val firebaseBom = "32.6.0"
    const val gms = "4.3.14"
    const val gradle = "8.1.2"
    const val kotlin = "1.9.20"
    const val kotlinCoroutines = "1.7.3"
    const val material = "1.10.0"
}
